[package]
name = "api-tester-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"
# 引入 similar 用于 Diff
similar = { version = "2.4", features = ["text", "unicode"] }
# 引入 serde 用于 JSON 处理
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
